#ifndef DEFINES_H__
#define DEFINES_H__

#define PWM_TOP_VALUE 1000

#define DELAY_DEBOUNCE_MS 50
#define DELAY_DOUBLE_CLICK_MS 400
#define DELAY_INTERVAL_FADE_MS 20

#define STEP_CHANGE_FADE_HUE 100
#define STEP_CHANGE_FADE_SATURATION 200
#define STEP_CHANGE_HUE 2
#define STEP_CHANGE_SATURATION 1
#define STEP_CHANGE_BRIGHT 1
#define COUNT_LEDS 4
#define COUNT_STATE_COLOR 4



#endif // DEFINES_H__