#ifndef DEFINES_H__
#define DEFINES_H__

#define PWM_TOP_VALUE 1000

#define MAX_VALUE_HUE 360
#define MAX_VALUE_SATURATION 100
#define MAX_VALUE_BRIGHTNESS 100


#define DELAY_DEBOUNCE_MS 200
#define DELAY_DOUBLE_CLICK_MS 400
#define DELAY_INTERVAL_FADE_MS 20

#define STEP_CHANGE_HUE 2
#define STEP_CHANGE_SATURATION 1
#define STEP_CHANGE_BRIGHT 1
#define COUNT_LEDS 4

// NEW DEFENITIONS:
#define STEP_CHANGE_YELLOW_COLOR_FAST 50
#define STEP_CHANGE_YELLOW_COLOR_SLOW 25
#define STEP_CHANGE_RED_COLOR 25
#define STEP_CHANGE_GREEN_COLOR 25
#define STEP_CHANGE_BLUE_COLOR 25 
// ================


#endif // DEFINES_H__